version: '3'

services:
  wiki:
    image: mediawiki
    ports:
      - "8080:80"
    volumes:
      - ~/LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      - MW_DB_HOST=db
      - MW_DB_PORT=3306
      - MW_DB_NAME=mediawiki
      - MW_DB_USER=wiki
      - MW_DB_PASS=DEP@ssw0rd

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: wiki
      MYSQL_PASSWORD: DEP@ssw0rd
    volumes:
      - dbvolume:/var/lib/mysql

volumes:
  dbvolume:

